/**
 * Project zones (docs/design/bits-arenas.md § Editor workflow) — the repo's own
 * zone files, listed, read and written by the dev server so switching arenas is
 * one click and "New arena" exists at all. Third sanctioned exception to
 * Realmsmith's "no server" (after the Forge and tileset serving): the browser
 * can't enumerate a folder it was never handed, and it certainly can't
 * regenerate the sim's zone registry. The File System Access path stays for
 * JSON outside the repo.
 *
 * Endpoints (all dev-only):
 *   GET  /zones                    → { zones: ProjectZone[] }  every zones/*.json
 *                                    under packages/<p>/src/zones and apps/<a>/assets/zones
 *   GET  /zones/file?path=<rel>    → the zone JSON
 *   PUT  /zones/file?path=<rel>    → write it back (2-space indent, trailing newline)
 *   POST /zones/new                → { from, id, name } clone `from` as <id>.json
 *                                    beside it; if that folder has a GENERATED
 *                                    index.ts (the sim's arena registry), rewrite it
 *                                    with one import + entry per JSON file.
 */
import type { IncomingMessage, ServerResponse } from "node:http";
import { existsSync } from "node:fs";
import { readFile, readdir, writeFile } from "node:fs/promises";
import { basename, dirname, join, relative, resolve, sep } from "node:path";
import type { Plugin } from "vite";

export interface ProjectZone {
  /** Repo-relative path, forward slashes — the key for every other call. */
  path: string;
  id: string;
  name: string;
  /** The package or app that owns the file (`blood-in-the-sand-sim`, `enter-the-gauntlet`). */
  owner: string;
  /** Whether the folder carries a generated registry (index.ts) — i.e. "New
   *  arena" here lands in the game automatically. */
  registry: boolean;
}

/** Zone ids are file names and registry keys — kebab, letter first. */
const ID_RE = /^[a-z][a-z0-9-]*$/;
const GENERATED_MARK = "// GENERATED by Realmsmith";

const json = (res: ServerResponse, code: number, body: unknown): void => {
  res.statusCode = code;
  res.setHeader("content-type", "application/json");
  res.end(JSON.stringify(body));
};

const readJson = <T>(req: IncomingMessage, maxBytes = 32 * 1024 * 1024): Promise<T> =>
  new Promise((resolvePromise, reject) => {
    const chunks: Buffer[] = [];
    let size = 0;
    req.on("data", (c: Buffer) => {
      size += c.length;
      if (size > maxBytes) {
        reject(new Error("request too large"));
        req.destroy();
        return;
      }
      chunks.push(c);
    });
    req.on("end", () => {
      try {
        resolvePromise(JSON.parse(Buffer.concat(chunks).toString("utf8")) as T);
      } catch (e) {
        reject(e);
      }
    });
    req.on("error", reject);
  });

/** Every zones folder the repo has: packages/<p>/src/zones, apps/<a>/assets/zones. */
const zoneDirs = async (repoRoot: string): Promise<{ dir: string; owner: string }[]> => {
  const out: { dir: string; owner: string }[] = [];
  for (const [parent, sub] of [
    ["packages", join("src", "zones")],
    ["apps", join("assets", "zones")],
  ] as const) {
    const base = join(repoRoot, parent);
    if (!existsSync(base)) continue;
    for (const e of await readdir(base, { withFileTypes: true })) {
      if (!e.isDirectory()) continue;
      const dir = join(base, e.name, sub);
      if (existsSync(dir)) out.push({ dir, owner: e.name });
    }
  }
  return out;
};

const hasRegistry = async (dir: string): Promise<boolean> => {
  const idx = join(dir, "index.ts");
  if (!existsSync(idx)) return false;
  return (await readFile(idx, "utf8")).startsWith(GENERATED_MARK);
};

/** Rewrite a folder's generated registry: one import + one entry per JSON. */
const regenerateRegistry = async (dir: string): Promise<void> => {
  const files = (await readdir(dir)).filter((f) => f.endsWith(".json")).sort();
  const ident = (f: string) => f.slice(0, -5).replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase()).replace(/[^A-Za-z0-9_]/g, "");
  const imports = files.map((f) => `import ${ident(f)} from "./${f}";`).join("\n");
  const entries = files.map((f) => `  ${JSON.stringify(f.slice(0, -5))}: ${ident(f)} as unknown as ZoneFile,`).join("\n");
  const text = `${GENERATED_MARK}'s "New arena" (apps/realmsmith/zonesServer/plugin.ts)
// — one import + one entry per zones/*.json. Hand-editing is fine too; the
// generator rewrites the whole file. Rotation (which arenas the server deals
// online) is NOT here: see ARENA_ROTATION in ../zone.ts.
import type { ZoneFile } from "@heroic/core";
${imports}

// JSON imports widen literal unions (e.g. kind: string), hence the casts —
// same idiom the gauntlet uses for its zone imports.
export const ARENAS: Record<string, ZoneFile> = {
${entries}
};
`;
  await writeFile(join(dir, "index.ts"), text);
};

export const zonesServerPlugin = (): Plugin => {
  let repoRoot = "";

  /** A repo-relative path is only valid if it is a .json directly inside a known zones dir. */
  const resolveZonePath = async (rel: string): Promise<string | null> => {
    if (!rel || rel.includes("..") || !rel.endsWith(".json")) return null;
    const abs = resolve(repoRoot, rel);
    for (const { dir } of await zoneDirs(repoRoot)) {
      if (dirname(abs) === dir) return abs;
    }
    return null;
  };
  const relPath = (abs: string) => relative(repoRoot, abs).split(sep).join("/");

  return {
    name: "realmsmith-zones",
    apply: "serve",
    configResolved(config) {
      repoRoot = resolve(config.root, "../..");
    },
    configureServer(server) {
      server.middlewares.use("/zones", (req, res) => {
        void (async () => {
          // Mounted at /zones, so req.url arrives with that prefix stripped.
          const u = new URL(req.url ?? "", "http://zones");
          const url = u.pathname;

          if (url === "" || url === "/") {
            const zones: ProjectZone[] = [];
            for (const { dir, owner } of await zoneDirs(repoRoot)) {
              const registry = await hasRegistry(dir);
              for (const f of (await readdir(dir)).filter((f) => f.endsWith(".json")).sort()) {
                try {
                  const z = JSON.parse(await readFile(join(dir, f), "utf8")) as { id?: unknown; name?: unknown };
                  zones.push({
                    path: relPath(join(dir, f)),
                    id: typeof z.id === "string" ? z.id : f.slice(0, -5),
                    name: typeof z.name === "string" ? z.name : f,
                    owner,
                    registry,
                  });
                } catch {
                  // Not a zone (or half-written) — skip rather than break the list.
                }
              }
            }
            return json(res, 200, { zones });
          }

          if (url === "/file") {
            const abs = await resolveZonePath(u.searchParams.get("path") ?? "");
            if (!abs || !existsSync(abs)) return json(res, 404, { error: "no such project zone" });
            if (req.method === "GET") {
              res.statusCode = 200;
              res.setHeader("content-type", "application/json");
              res.setHeader("cache-control", "no-cache");
              return res.end(await readFile(abs));
            }
            if (req.method === "PUT") {
              const zone = await readJson<unknown>(req);
              // Same on-disk shape as the generator/File-System path: minimal diffs.
              await writeFile(abs, JSON.stringify(zone, null, 2) + "\n");
              return json(res, 200, { ok: true });
            }
            return json(res, 405, { error: "GET or PUT" });
          }

          if (url === "/new" && req.method === "POST") {
            const body = await readJson<{ from?: unknown; id?: unknown; name?: unknown }>(req);
            const id = typeof body.id === "string" ? body.id.trim() : "";
            const name = typeof body.name === "string" ? body.name.trim() : "";
            if (!ID_RE.test(id)) return json(res, 400, { error: "id must be kebab-case, letter first (e.g. arena-01)" });
            if (!name) return json(res, 400, { error: "a display name is required" });
            const from = await resolveZonePath(typeof body.from === "string" ? body.from : "");
            if (!from || !existsSync(from)) return json(res, 404, { error: "template zone not found" });
            const dir = dirname(from);
            const target = join(dir, `${id}.json`);
            if (existsSync(target)) return json(res, 409, { error: `${basename(target)} already exists` });
            const zone = JSON.parse(await readFile(from, "utf8")) as Record<string, unknown>;
            zone.id = id;
            zone.name = name;
            await writeFile(target, JSON.stringify(zone, null, 2) + "\n");
            const registry = await hasRegistry(dir);
            if (registry) await regenerateRegistry(dir);
            return json(res, 200, { path: relPath(target), id, name, registry });
          }

          json(res, 404, { error: "not found" });
        })().catch((e: unknown) => json(res, 500, { error: String(e) }));
      });
    },
  };
};
