export { createDb, ensureSchema, type Db } from "./db";
export {
  registerPlayer,
  findPlayerByToken,
  mintPlayerToken,
  type Registration,
} from "./players";
export {
  linkAccount,
  restoreAccount,
  unlinkAccount,
  linkedClerkUserId,
  type LinkInput,
  type LinkOutcome,
} from "./accounts";
export { gloryBalance, recordGlory, type GloryEntry } from "./glory";
export { signetBalance, recordSignet, type SignetEntry } from "./signets";
export {
  creditIapSignets,
  exchangeGloryForSignet,
  unlockWithSignet,
  type ExchangeInput,
  type ExchangeResult,
  type IapCreditInput,
  type IapCreditResult,
  type UnlockInput,
  type UnlockResult,
} from "./store";
export {
  RATING_START,
  RATING_FLOOR,
  PLACEMENT_MATCHES,
  K_PLACEMENT,
  K_SETTLED,
  GLORY_WIN_FLOOR,
  GLORY_WIN_RANGE,
  GLORY_LOSS,
  TIERS,
  TIER_GRACE,
  RUNGS,
  expectedScore,
  kFactor,
  updateRating,
  tierFor,
  tierFloorOf,
  nextTierAbove,
  displayTierFor,
  rungFor,
  rungAbove,
  displayRungFor,
  displayFloorOf,
  rankChangeBetween,
  winnerGlory,
  teamMean,
  loserGlory,
  type Rung,
  type RatingUpdateInput,
  type TierName,
} from "./elo";
export {
  achievementCounters,
  achievementUnlocks,
  applyMatchAchievements,
  entitlementsOf,
  gloryEarned,
  type AchievementAward,
  type AchievementUnlockRecord,
  type EntitlementRecord,
  type MatchAchievementsInput,
} from "./achievements";
export {
  getRating,
  recordRankedMatch,
  recordRankedBotMatch,
  leaderboard,
  rankedSummary,
  recentForm,
  type RankedRating,
  type RankedMatchInput,
  type RankedSubjectInput,
  type RankedBotMatchInput,
  type RankedMatchResult,
  type RankedSideResult,
  type LeaderboardEntry,
} from "./ranked";
export {
  FEEDBACK_KINDS,
  FEEDBACK_MESSAGE_MAX,
  FEEDBACK_EMAIL_MAX,
  FEEDBACK_STAMP_MAX,
  recordFeedback,
  listFeedback,
  type FeedbackInput,
  type FeedbackKind,
  type FeedbackRecord,
} from "./feedback";
