// GENERATED by Realmsmith's "New arena" (apps/realmsmith/zonesServer/plugin.ts)
// — one import + one entry per zones/*.json. Hand-editing is fine too; the
// generator rewrites the whole file. Rotation (which arenas the server deals
// online) is NOT here: see ARENA_ROTATION in ../zone.ts.
import type { ZoneFile } from "@heroic/core";
import arena00 from "./arena-00.json";
import grasslands from "./grasslands.json";

// JSON imports widen literal unions (e.g. kind: string), hence the casts —
// same idiom the gauntlet uses for its zone imports.
export const ARENAS: Record<string, ZoneFile> = {
  "arena-00": arena00 as unknown as ZoneFile,
  "grasslands": grasslands as unknown as ZoneFile,
};
