import type { AudioManifest } from "@heroic/engine";
import { ANNOUNCER_MANIFEST } from "./announcer";
import { SFX_MANIFEST } from "./sfxManifest.generated";

/**
 * Clip name → bundled audio file. The SFX catalogue (`catalogue.ts`) names
 * clips that resolve here; the AudioDirector looks them up. A name the catalogue
 * uses with no entry here warns once and stays silent, so the catalogue is safe
 * to author ahead of the files.
 *
 * The SFX banks are NOT listed by hand any more (2026-09-06): every
 * `<bank>_<n>.mp3` in `assets/audio/sfx/` is in `sfxManifest.generated.ts`,
 * rewritten by the Realmsmith Forge on each save/remove (or `bun run
 * sfx:manifest` in apps/realmsmith after moving files by hand), and the
 * catalogue derives each bank's clip list from those keys. Adding a take is
 * generate → keep → save in the Forge; nothing to paste, nothing to count.
 *
 * The booming announcer voice (`announce_*`) is NOT in that folder: it's a
 * swappable, sellable PACK, so it lives in `announcer.ts` (its own
 * `announcer/<pack>/` folders) and is spread in below as EVERY pack's clips
 * under pack-namespaced names — playSound remaps the catalogue's stable names
 * to the active pack.
 */
export const AUDIO_MANIFEST: AudioManifest = {
    // Every `<bank>_<n>.mp3` in assets/audio/sfx — GENERATED by the Realmsmith
    // Forge on each save/remove (sfxManifest.generated.ts); never hand-edit.
    ...SFX_MANIFEST,

    // ALL announcer packs (announcer.ts) — `<pack>:announce_first_blood_1`, …
    ...ANNOUNCER_MANIFEST,
};
