// GENERATED by `bun run sfx:manifest` in apps/realmsmith
// (forge/sfxManifest.ts) — do not edit. One line per `<song>.mp3` in
// assets/audio/music; the pool is the keys (docs/design/bits-music.md).

/* eslint-disable @typescript-eslint/no-require-imports */
export const MUSIC_MANIFEST: Record<string, number> = {
  berserker: require("../../assets/audio/music/berserker.mp3"),
  carthage: require("../../assets/audio/music/carthage.mp3"),
  chant: require("../../assets/audio/music/chant.mp3"),
  cretan: require("../../assets/audio/music/cretan.mp3"),
  dread: require("../../assets/audio/music/dread.mp3"),
  druid: require("../../assets/audio/music/druid.mp3"),
  duduk: require("../../assets/audio/music/duduk.mp3"),
  gaul: require("../../assets/audio/music/gaul.mp3"),
  hellas: require("../../assets/audio/music/hellas.mp3"),
  hispania: require("../../assets/audio/music/hispania.mp3"),
  horns: require("../../assets/audio/music/horns.mp3"),
  kabuki: require("../../assets/audio/music/kabuki.mp3"),
  legion: require("../../assets/audio/music/legion.mp3"),
  mauryan: require("../../assets/audio/music/mauryan.mp3"),
  nile: require("../../assets/audio/music/nile.mp3"),
  north: require("../../assets/audio/music/north.mp3"),
  opera: require("../../assets/audio/music/opera.mp3"),
  pharaoh: require("../../assets/audio/music/pharaoh.mp3"),
  pontic: require("../../assets/audio/music/pontic.mp3"),
  shaman: require("../../assets/audio/music/shaman.mp3"),
  taiko: require("../../assets/audio/music/taiko.mp3"),
  warring: require("../../assets/audio/music/warring.mp3"),
};
