// GENERATED by `bun run arena:cards` (apps/realmsmith/scripts/arena-cards.ts)
// — one require per rendered card in assets/arenas. Don't hand-edit; re-run the
// script after an arena's art changes or a new arena lands.
export const ARENA_CARD_IMAGES: Record<string, number> = {
  "arena-00": require("../../assets/arenas/arena-00.png") as number,
  "grasslands": require("../../assets/arenas/grasslands.png") as number,
  "desert-1": require("../../assets/arenas/desert-1.png") as number,
};
