import type { TerrainDef } from "@heroic/core";
import { ANCIENT_TERRAINS } from "./ancient";

/**
 * Terrain brushes by tileset name (docs/design/tilesets.md § Terrain brushes).
 * Editor-only: the games never autotile, they just draw the ids the brush wrote.
 * Tables are generated by `scripts/repack-tileset.py` from the pack's Tiled
 * metadata — a tileset with no entry here simply offers no terrains.
 */
export const TERRAINS: Record<string, Record<string, TerrainDef>> = {
  ancient: ANCIENT_TERRAINS,
};
