/**
 * The generated SFX manifest (docs/design/asset-forge.md § Sound banks).
 *
 * Every `<bank>_<n>.mp3` in the game's SFX folder becomes one `require()`
 * line in `src/audio/sfxManifest.generated.ts`, rewritten by the Forge after
 * every save and remove (and by `bun run sfx:manifest` for a manual sync). The
 * game's catalogue derives each bank's clip list from these keys at load, so
 * adding a take to a bank is: generate → keep → save. No hand-edited lines,
 * no counting takes.
 *
 * Only numbered files are picked up; anything else in the folder is listed in
 * a comment so a stray file is visible rather than silently ignored.
 */
import { readdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const NUMBERED = /^([a-z][a-z0-9_]*)_(\d+)\.mp3$/;

export interface BankFile {
  file: string;
  bank: string;
  n: number;
}

/** The numbered mp3s in a folder, sorted by bank then take number. */
export const listBankFiles = async (dir: string): Promise<{ files: BankFile[]; strays: string[] }> => {
  let names: string[] = [];
  try {
    names = await readdir(dir);
  } catch {
    return { files: [], strays: [] };
  }
  const files: BankFile[] = [];
  const strays: string[] = [];
  for (const file of names) {
    const m = NUMBERED.exec(file);
    if (m) files.push({ file, bank: m[1]!, n: Number(m[2]) });
    else if (file.endsWith(".mp3")) strays.push(file);
  }
  files.sort((a, b) => (a.bank === b.bank ? a.n - b.n : a.bank < b.bank ? -1 : 1));
  return { files, strays };
};

/** The TypeScript source of the generated manifest. `requireDir` is the
 * relative path from the generated file to the SFX folder. */
export const renderSfxManifest = (files: BankFile[], strays: string[], requireDir: string): string => {
  const lines = files.map((f) => `  ${f.file.replace(/\.mp3$/, "")}: require("${requireDir}/${f.file}"),`);
  const strayNote =
    strays.length > 0
      ? `\n// Not picked up (not \`<bank>_<n>.mp3\`): ${strays.join(", ")}\n`
      : "";
  return (
    "// GENERATED by the Realmsmith Forge (apps/realmsmith/forge/sfxManifest.ts) —\n" +
    "// do not edit. One line per `<bank>_<n>.mp3` in assets/audio/sfx; rewritten on\n" +
    "// every Forge save/remove, or `bun run sfx:manifest` in apps/realmsmith.\n" +
    "// The catalogue derives each bank's clips from these keys (catalogue.ts `bank`).\n" +
    strayNote +
    "\n/* eslint-disable @typescript-eslint/no-require-imports */\n" +
    "export const SFX_MANIFEST: Record<string, number> = {\n" +
    lines.join("\n") +
    "\n};\n"
  );
};

export interface SfxManifestTarget {
  /** Absolute path of the SFX folder. */
  dir: string;
  /** Absolute path of the generated .ts file. */
  out: string;
  /** Relative path from `out`'s folder to `dir`, as the require() prefix. */
  requireDir: string;
}

/** Rewrite the generated manifest from the folder's current contents. */
export const writeSfxManifest = async (target: SfxManifestTarget): Promise<{ count: number; strays: string[] }> => {
  const { files, strays } = await listBankFiles(target.dir);
  await writeFile(target.out, renderSfxManifest(files, strays, target.requireDir));
  return { count: files.length, strays };
};

/** Where the BITS manifest lives, from the repo root + the spec's destination. */
export const bitsManifestTarget = (repoRoot: string, destination: string): SfxManifestTarget => ({
  dir: join(repoRoot, destination),
  out: join(repoRoot, "apps/blood-in-the-sand/src/audio/sfxManifest.generated.ts"),
  requireDir: "../../assets/audio/sfx",
});

// ── Music ──────────────────────────────────────────────────────────────────
// The battle-music pool (docs/design/bits-music.md) is one `<song>.mp3` per
// song, no take numbers, Suno-made by hand — so the Forge never writes here,
// but `bun run sfx:manifest` keeps its generated manifest in step the same way.

const SONG = /^([a-z][a-z0-9_]*)\.mp3$/;

export const listSongs = async (dir: string): Promise<string[]> => {
  let names: string[] = [];
  try {
    names = await readdir(dir);
  } catch {
    return [];
  }
  return names.filter((f) => SONG.test(f)).sort();
};

export const renderMusicManifest = (songs: string[], requireDir: string): string =>
  "// GENERATED by `bun run sfx:manifest` in apps/realmsmith\n" +
  "// (forge/sfxManifest.ts) — do not edit. One line per `<song>.mp3` in\n" +
  "// assets/audio/music; the pool is the keys (docs/design/bits-music.md).\n\n" +
  "/* eslint-disable @typescript-eslint/no-require-imports */\n" +
  "export const MUSIC_MANIFEST: Record<string, number> = {\n" +
  songs.map((f) => `  ${f.replace(/\.mp3$/, "")}: require("${requireDir}/${f}"),`).join("\n") +
  "\n};\n";

export const writeMusicManifest = async (target: SfxManifestTarget): Promise<number> => {
  const songs = await listSongs(target.dir);
  await writeFile(target.out, renderMusicManifest(songs, target.requireDir));
  return songs.length;
};

export const bitsMusicTarget = (repoRoot: string): SfxManifestTarget => ({
  dir: join(repoRoot, "apps/blood-in-the-sand/assets/audio/music"),
  out: join(repoRoot, "apps/blood-in-the-sand/src/audio/musicManifest.generated.ts"),
  requireDir: "../../assets/audio/music",
});
